### ISSUE TITLE
stuck in video UI, no update, no installation, just webui operation

### ISSUE THREAD

**Issue by lida2003** [stephendade/Rpanion-server#247]
I have got the [app.log](https://github.com/user-attachments/files/17162947/app.log). But I didn't find any infor useful for me.

It doesn't work with warm boot, cold boot, can't enter video webGUI.

From ssh console: 
```
daniel@rpanion:~/Rpanion-server $ python3 --version
Python 3.9.2
daniel@rpanion:~/Rpanion-server $ ls -l /usr/local/lib/python3.9/
total 4
drwxr-xr-x 6 root root 4096 Feb  9  2024 dist-packages
daniel@rpanion:~/Rpanion-server $ which python3
/usr/bin/python3
daniel@rpanion:~/Rpanion-server $ pip install --force-reinstall importlib-metadata
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1189, in _install_external_importers
  File "<frozen importlib._bootstrap_external>", line 1634, in _install
  File "<frozen importlib._bootstrap_external>", line 1605, in _setup
ImportError: importlib requires posix or nt
Fatal Python error: init_importlib_external: external importer setup failed
Python runtime state: core initialized

Current thread 0x0000007fb110e040 (most recent call first):
<no Python frame>
daniel@rpanion:~/Rpanion-server $ python3 -v
import _frozen_importlib # frozen
import _imp # builtin
import '_thread' # <class '_frozen_importlib.BuiltinImporter'>
import '_warnings' # <class '_frozen_importlib.BuiltinImporter'>
import '_weakref' # <class '_frozen_importlib.BuiltinImporter'>
import '_frozen_importlib_external' # <class '_frozen_importlib.FrozenImporter'>
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1189, in _install_external_importers
  File "<frozen importlib._bootstrap_external>", line 1634, in _install
  File "<frozen importlib._bootstrap_external>", line 1605, in _setup
ImportError: importlib requires posix or nt
Fatal Python error: init_importlib_external: external importer setup failed
Python runtime state: core initialized

Current thread 0x0000007fba5ed040 (most recent call first):
<no Python frame>

```

- It's webGUI and popup messages.
```
Traceback (most recent call last): File "<frozen importlib._bootstrap>", line 1189, in _install_external_importers File "<frozen importlib._bootstrap_external>", line 1634, in _install File "<frozen importlib._bootstrap_external>", line 1605, in _setup ImportError: importlib requires posix or nt Fatal Python error: init_importlib_external: external importer setup failed Python runtime state: core initialized Current thread 0x0000007f893f2040 (most recent call first): <no Python frame> 
```

![图片](https://github.com/user-attachments/assets/9cc8517d-58bc-4eb2-891f-6e5422ecd1b7)

![图片](https://github.com/user-attachments/assets/8e67f393-210e-4295-9d75-48e6756d21d7)

**Comment by lida2003** [comment]
I think it might be rootfs issue. Maybe some thing on the sd is lost. I'll re-flash the sd card.

**Comment by lida2003** [comment]
Re-install fix the issue. Probably fs issue.
